import { google } from "googleapis";
import { refreshAccessToken, isTokenExpired, setOAuth2Credentials } from "./google-oauth-client";
import tokenStorage from "./google-token-storage";
import type { GoogleOAuthToken } from "@/types/index";

/**
 * 사용자의 현재 토큰 조회 및 갱신 (필요시)
 *
 * 🔥 핵심 동작:
 * ───────────────────────────────────────────────────────
 * 1️⃣ 저장된 토큰 확인
 * 2️⃣ 만료 여부 체크 (5분 버퍼로 미리 갱신)
 * 3️⃣ refresh_token으로 새로운 access_token 발급
 * 4️⃣ 토큰 저장소 업데이트
 * 5️⃣ 파일 업로드 계속 진행
 *
 * 📌 이 로직이 있어야:
 *   - 블로그 자동 업로드 가능
 *   - 사용자가 계속 로그인 상태 유지
 *   - 완전 자동화 가능 ✅
 */
async function getValidToken(userEmail: string): Promise<GoogleOAuthToken> {
  console.log(`🔍 사용자 토큰 조회: ${userEmail}`);

  const token = tokenStorage.get(userEmail);

  if (!token) {
    throw new Error(`저장된 토큰이 없습니다: ${userEmail}`);
  }

  // 토큰이 만료되었는지 확인 (5분 버퍼 포함)
  if (isTokenExpired(token.expiry_date)) {
    console.log(`⚠️ 토큰이 곧 만료됩니다. Refresh token으로 갱신 중...`);
    console.log("💡 이 자동 갱신이 가능한 이유: access_type=offline + prompt=consent");

    if (!token.refresh_token) {
      throw new Error(
        "❌ Refresh token이 없어서 토큰을 갱신할 수 없습니다!\n" +
        "원인: 처음 로그인 시 access_type=offline 또는 prompt=consent 옵션 누락\n" +
        "해결: 다시 로그인해주세요 (Google 보안에서 앱 삭제 후)"
      );
    }

    // Refresh token으로 새로운 access token 발급
    const newTokenData = await refreshAccessToken(token.refresh_token);

    // 토큰 업데이트
    tokenStorage.update(userEmail, newTokenData.access_token, newTokenData.expiry_date);

    // 업데이트된 토큰 반환
    const updatedToken = tokenStorage.get(userEmail);
    if (!updatedToken) {
      throw new Error("토큰 업데이트 실패");
    }

    return updatedToken;
  }

  console.log("✅ 유효한 토큰 확인됨");
  return token;
}

/**
 * Google Drive에 파일 업로드
 *
 * @param userEmail - 사용자 이메일
 * @param fileName - 업로드할 파일명
 * @param fileContent - 파일 내용 (문자열 또는 Buffer)
 * @param mimeType - MIME 타입 (기본값: text/plain)
 * @returns 업로드된 파일 ID
 */
export async function uploadFileToDrive(
  userEmail: string,
  fileName: string,
  fileContent: string | Buffer,
  mimeType: string = "text/plain"
): Promise<string> {
  try {
    console.log(`📤 Google Drive 업로드 시작: ${fileName}`);

    // 1️⃣ 유효한 토큰 가져오기 (자동 갱신 포함)
    const token = await getValidToken(userEmail);

    // 2️⃣ Google API 클라이언트 생성
    const oauth2Client = new google.auth.OAuth2(
      process.env.GOOGLE_CLIENT_ID,
      process.env.GOOGLE_CLIENT_SECRET,
      process.env.GOOGLE_REDIRECT_URI
    );

    setOAuth2Credentials(oauth2Client, token);

    // 3️⃣ Google Drive API 초기화
    const drive = google.drive({
      version: "v3",
      auth: oauth2Client,
    });

    // 4️⃣ 파일 업로드
    console.log(`📝 파일 생성/업데이트: ${fileName}`);

    const response = await drive.files.create({
      requestBody: {
        name: fileName,
        mimeType,
        description: "Auto-generated by Blog AI",
        parents: undefined, // 최상위 디렉토리에 저장
      },
      media: {
        mimeType,
        body: fileContent,
      },
      fields: "id, webViewLink", // 반환 필드
    });

    const fileId = response.data.id;
    const webViewLink = response.data.webViewLink;

    console.log("✅ 파일 업로드 완료");
    console.log(`📁 파일 ID: ${fileId}`);
    console.log(`🔗 웹 링크: ${webViewLink}`);

    return fileId || "";
  } catch (error) {
    console.error("❌ Google Drive 업로드 실패:", error);
    throw error;
  }
}

/**
 * Google Drive에서 파일 업데이트
 *
 * @param userEmail - 사용자 이메일
 * @param fileId - 업데이트할 파일 ID
 * @param fileContent - 새로운 파일 내용
 * @param mimeType - MIME 타입
 */
export async function updateFileInDrive(
  userEmail: string,
  fileId: string,
  fileContent: string | Buffer,
  mimeType: string = "text/plain"
): Promise<void> {
  try {
    console.log(`📝 Google Drive 파일 업데이트: ${fileId}`);

    // 유효한 토큰 가져오기
    const token = await getValidToken(userEmail);

    // Google API 클라이언트 생성
    const oauth2Client = new google.auth.OAuth2(
      process.env.GOOGLE_CLIENT_ID,
      process.env.GOOGLE_CLIENT_SECRET,
      process.env.GOOGLE_REDIRECT_URI
    );

    setOAuth2Credentials(oauth2Client, token);

    const drive = google.drive({
      version: "v3",
      auth: oauth2Client,
    });

    // 파일 업데이트
    await drive.files.update({
      fileId,
      media: {
        mimeType,
        body: fileContent,
      },
    });

    console.log("✅ 파일 업데이트 완료");
  } catch (error) {
    console.error("❌ Google Drive 파일 업데이트 실패:", error);
    throw error;
  }
}

/**
 * Google Drive에서 파일 삭제
 *
 * @param userEmail - 사용자 이메일
 * @param fileId - 삭제할 파일 ID
 */
export async function deleteFileFromDrive(
  userEmail: string,
  fileId: string
): Promise<void> {
  try {
    console.log(`🗑️ Google Drive 파일 삭제: ${fileId}`);

    const token = await getValidToken(userEmail);

    const oauth2Client = new google.auth.OAuth2(
      process.env.GOOGLE_CLIENT_ID,
      process.env.GOOGLE_CLIENT_SECRET,
      process.env.GOOGLE_REDIRECT_URI
    );

    setOAuth2Credentials(oauth2Client, token);

    const drive = google.drive({
      version: "v3",
      auth: oauth2Client,
    });

    await drive.files.delete({
      fileId,
    });

    console.log("✅ 파일 삭제 완료");
  } catch (error) {
    console.error("❌ Google Drive 파일 삭제 실패:", error);
    throw error;
  }
}

/**
 * 사용자 로그아웃 (토큰 삭제)
 *
 * @param userEmail - 사용자 이메일
 */
export function logoutUser(userEmail: string): void {
  console.log(`👋 사용자 로그아웃: ${userEmail}`);
  tokenStorage.delete(userEmail);
  console.log("✅ 토큰 삭제 완료");
}

/**
 * 사용자 토큰 정보 조회 (디버깅용)
 */
export function getUserTokenInfo(userEmail: string) {
  const token = tokenStorage.get(userEmail);

  if (!token) {
    return null;
  }

  return {
    email: userEmail,
    hasAccessToken: !!token.access_token,
    hasRefreshToken: !!token.refresh_token,
    isTokenExpired: isTokenExpired(token.expiry_date),
    expiryDate: new Date(token.expiry_date),
  };
}
